name: data-streaming-project

on:
  push:
    branches:
      - main

jobs:
  run-tests:
    name: run-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Python Setup
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install Dependencies
        run: |
          make create-environment
          source venv/bin/activate
          make requirements
      - name: Run Tests and Checks
        run: |
          source venv/bin/activate
          make run-checks
  package-layer:
    name: package-lambda-layer
    runs-on: ubuntu-latest
    needs: run-tests
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Python Setup
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: |
          make create-environment
          source venv/bin/activate
          make requirements

      - name: Build Lambda Layer Zip
        run: |
          source venv/bin/activate
          mkdir -p python
          cp -r venv/lib/python3.12/site-packages/* python/
          zip -r requests_layer.zip python

  # deploy-lambda:
  #   name: deploy-lambda
  #   runs-on: ubuntu-latest
  #   environment: development
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4

  #     - name: Configure AWS Credentials
  #       uses: aws-actions/configure-aws-credentials@v4
  #       with:
  #         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #         aws-region: ${{ secrets.AWS_REGION }}

  #     - name: Terraform Setup
  #       uses: hashicorp/setup-terraform@v3

  #     - name: Terraform Init
  #       working-directory: terraform
  #       run: terraform init

  #     - name: Terraform Plan
  #       working-directory: terraform
  #       run: terraform plan

  #     - name: Terraform Apply
  #       working-directory: terraform
  #       run: terraform apply -auto-approve